.TH "dbmanager.h" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbmanager.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QtSql>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QQueue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbManager\fP"
.br
.RI "Most functionality of the \fBdbManager\fP class is to load the campus names and the the distance between the selected campus and loading souvenirs name and price and lastly the ability to create a data table for the shopping cart\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
