.TH "displaycollegewindow.cpp" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
displaycollegewindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'displaycollegewindow\&.h'\fP
.br
\fC#include 'ui_displaycollegewindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
