.TH "displaycollegewindow.h" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
displaycollegewindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdisplayCollegeWindow\fP"
.br
.RI "Most functionality of the \fBdisplayCollegeWindow\fP class is show the initial college list in the from of a sql database\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
