.TH "global.h" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QAxObject>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBInputCollegeList\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< \fBInputCollegeList\fP > \fBCollegeList\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "vector<\fBInputCollegeList\fP> CollegeList"
global vetor variable used for stord in the new college data 
.PP
Definition at line \fB31\fP of file \fBglobal\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
