.TH "global" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
global \- Most functionality of the global file is to created a global struct for storing the new input data of college information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global\&.h>\fP
.SH "Detailed Description"
.PP 
Most functionality of the global file is to created a global struct for storing the new input data of college information\&. 

/** 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
