.TH "inputcollege.h" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputcollege.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QAxObject>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <QtSql>\fP
.br
\fC#include <QQueue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputCollege\fP"
.br
.RI "Most functionality of the \fBInputCollege\fP class is to reading in the new college data as a excel file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
