.TH "InputCollegeList" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputCollegeList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <global\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBstartingCollege\fP"
.br
.ti -1c
.RI "string \fBendingCollege\fP"
.br
.ti -1c
.RI "double \fBdistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for the information about a new college data\&. 
.PP
Definition at line \fB25\fP of file \fBglobal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double InputCollegeList::distance"
the distance between starting college and ending college 
.PP
Definition at line \fB28\fP of file \fBglobal\&.h\fP\&.
.SS "string InputCollegeList::endingCollege"
ending college name 
.PP
Definition at line \fB27\fP of file \fBglobal\&.h\fP\&.
.SS "string InputCollegeList::startingCollege"
starting college name 
.PP
Definition at line \fB26\fP of file \fBglobal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
