.TH "inputcollege.cpp" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputcollege.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'inputcollege\&.h'\fP
.br
\fC#include 'ui_inputcollege\&.h'\fP
.br
\fC#include 'global\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
