.TH "loginpage.cpp" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loginpage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'loginpage\&.h'\fP
.br
\fC#include 'ui_loginpage\&.h'\fP
.br
\fC#include 'maintenance\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
