.TH "loginpage.h" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loginpage.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBloginpage\fP"
.br
.RI "Most functionality of the loginpage class is to created a login page for the administrator to gain access to the maintenace\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
