.TH "mainwindow.h" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QtSql>\fP
.br
\fC#include <QtDebug>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
