.TH "maintenance" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maintenance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <maintenance\&.h>\fP
.PP
Inherits \fBQDialog\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmaintenance\fP (\fBQWidget\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~maintenance\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButton_2_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::maintenance * \fBui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBmaintenance\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "maintenance::maintenance (\fBQWidget\fP * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB18\fP of file \fBmaintenance\&.cpp\fP\&.
.SS "maintenance::~maintenance ()"

.PP
Definition at line \fB26\fP of file \fBmaintenance\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void maintenance::on_pushButton_2_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB31\fP of file \fBmaintenance\&.cpp\fP\&.
.SS "void maintenance::on_pushButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB42\fP of file \fBmaintenance\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Ui::maintenance* maintenance::ui\fC [private]\fP"

.PP
Definition at line \fB30\fP of file \fBmaintenance\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
