.TH "MainWindow" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits \fBQMainWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (\fBQWidget\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_startCollegeTour_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_Maintenance_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::MainWindow * \fBui\fP"
.br
.ti -1c
.RI "\fBdbManager\fP \fBm_database\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBmainwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (\fBQWidget\fP * parent = \fCnullptr\fP)"

.PP
Definition at line \fB21\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "MainWindow::~MainWindow ()"

.PP
Definition at line \fB28\fP of file \fBmainwindow\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MainWindow::on_Maintenance_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB42\fP of file \fBmainwindow\&.cpp\fP\&.
.SS "void MainWindow::on_startCollegeTour_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB33\fP of file \fBmainwindow\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdbManager\fP MainWindow::m_database\fC [private]\fP"

.PP
Definition at line \fB30\fP of file \fBmainwindow\&.h\fP\&.
.SS "Ui::MainWindow* MainWindow::ui\fC [private]\fP"

.PP
Definition at line \fB29\fP of file \fBmainwindow\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
