.TH "maintenance.cpp" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maintenance.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'maintenance\&.h'\fP
.br
\fC#include 'ui_maintenance\&.h'\fP
.br
\fC#include 'inputcollege\&.h'\fP
.br
\fC#include 'souveniraddandedit\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
