.TH "maintenance.h" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maintenance.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QAxObject>\fP
.br
\fC#include 'souveniraddandedit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaintenance\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
