.TH "md__r_e_a_d_m_e" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- CS1D-College-Tour 
.PP
Project college tour description: 
.PP
.nf
This program is a software that reads data and stores it in a data structure\&. 
The program must have the ability to hold the names of at least 20 college campuses 
(the initial data contains 11 campuses) and their corresponding traditional 
souvenirs (up to seven per campus)\&. Also the program will be used to allow perspective
college students to plan their college experience\&. Last the program will provide the
ability to modify information related to the traditional souvenirs (such as adding
new souvenirs, changing a price of a souvenir, or deleting a souvenir)\&.

.fi
.PP
 Basic functionality: 
.PP
.nf
Displaying the initial information 

Planning a trips

Maintenance

purchase multiple traditional souvenirs

.fi
.PP
 Scrum Team: 
.PP
.nf
Scrum Master: Peijun Zhao\&.

Project Owners: Yaqub Hasan

Project Members: Peijun Zhao, Yaqub Hasan, Yuan Cao, Mark Qiu, Nico Julian

.fi
.PP
 
