.TH "md__c_o_d_e__o_f__c_o_n_d_u_c_t" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_o_d_e__o_f__c_o_n_d_u_c_t \- CS1D College Tour Application 
.PP

.SH "Scope Of the Program"
.PP
This program is a software that reads data and stores it in a data structure\&. The program must have the ability to hold the names of at least 20 college campuses (the initial data contains 11 campuses) and their corresponding traditional souvenirs (up to seven per campus)\&. Also the program will be used to allow perspective college students to plan their college experience\&. Last the program will provide the ability to modify information related to the traditional souvenirs (such as adding new souvenirs, changing a price of a souvenir, or deleting a souvenir)\&.
.SH "Our Ruls"
.PP
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation\&.
.PP
We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community\&.
.SH "Our Standards"
.PP
Examples of behavior that contributes to a positive environment for our community include:
.PP
.IP "\(bu" 2
Demonstrating empathy and kindness toward other people
.IP "\(bu" 2
Being respectful of differing opinions, viewpoints, and experiences
.IP "\(bu" 2
Giving and gracefully accepting constructive feedback
.IP "\(bu" 2
Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
.IP "\(bu" 2
Focusing on what is best not just for us as individuals, but for the overall community
.PP
.PP
Examples of unacceptable behavior include:
.PP
.IP "\(bu" 2
The use of sexualized language or imagery, and sexual attention or advances of any kind
.IP "\(bu" 2
Trolling, insulting or derogatory comments, and personal or political attacks
.IP "\(bu" 2
Public or private harassment
.IP "\(bu" 2
Publishing others' private information, such as a physical or email address, without their explicit permission
.IP "\(bu" 2
Other conduct which could reasonably be considered inappropriate in a professional setting
.PP
.SH "Enforcement Responsibilities"
.PP
Community leaders are responsible for clarifying and enforcing our standards of acceptable behavior and will take appropriate and fair corrective action in response to any behavior that they deem inappropriate, threatening, offensive, or harmful\&.
.PP
The Scrum Master and the Project owner of this project have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate\&.
.SH "Our Code Standers"
.PP
Variable naming conventions (Camel case) Class and function naming conventions Clear and concise comments Indentations Portability Reusability and scalability Testing your own code befor pushing to main branch\&.
.SH "Scrum Team:"
.PP
Scrum Master: Peijun Zhao\&.
.PP
Project Owners: Yaqub Hasan
.PP
Project Members: Peijun Zhao, Yaqub Hasan, Yuan Cao, Mark Qiu, Nico Julian 
