.TH "planTripWindow::Souvenir" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
planTripWindow::Souvenir
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plantripwindow\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBsouvName\fP"
.br
.ti -1c
.RI "QString \fBcampus\fP"
.br
.ti -1c
.RI "double \fBcost\fP"
.br
.ti -1c
.RI "int \fBquantity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for the information about a souvenir purchased by the student\&. 
.PP
Definition at line \fB28\fP of file \fBplantripwindow\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "QString planTripWindow::Souvenir::campus"
Campus of origin 
.PP
Definition at line \fB31\fP of file \fBplantripwindow\&.h\fP\&.
.SS "double planTripWindow::Souvenir::cost"
Cost of the souvenir 
.PP
Definition at line \fB32\fP of file \fBplantripwindow\&.h\fP\&.
.SS "int planTripWindow::Souvenir::quantity"
Number of souvenirs purchased 
.PP
Definition at line \fB33\fP of file \fBplantripwindow\&.h\fP\&.
.SS "QString planTripWindow::Souvenir::souvName"
\fBSouvenir\fP name 
.PP
Definition at line \fB30\fP of file \fBplantripwindow\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
