.TH "plantripwindow.h" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plantripwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QAbstractTableModel>\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplanTripWindow\fP"
.br
.RI "Most functionality of the \fBplanTripWindow\fP class is to give the student options on how they would like to plan their trip and buying multiple souvenits at differnt colleges\&. "
.ti -1c
.RI "struct \fBplanTripWindow::Souvenir\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
