.TH "QDialog" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBInputCollege\fP, \fBdisplayCollegeWindow\fP, \fBloginpage\fP, \fBmaintenance\fP, \fBplanTripWindow\fP, \fBsouvenirAddandEdit\fP, and \fBuserInterface\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
