.TH "souveniraddandedit.cpp" 3 "Sun Mar 19 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
souveniraddandedit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'souveniraddandedit\&.h'\fP
.br
\fC#include 'ui_souveniraddandedit\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
