.TH "userinterface.cpp" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userinterface.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'userinterface\&.h'\fP
.br
\fC#include 'ui_userinterface\&.h'\fP
.br
\fC#include 'plantripwindow\&.h'\fP
.br
\fC#include 'displaycollegewindow\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
