.TH "userwindow.cpp" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'userwindow\&.h'\fP
.br
\fC#include 'ui_userwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
