.TH "userWindow" 3 "Sat Mar 18 2023" "CS1D-College-Tour" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <userwindow\&.h>\fP
.PP
Inherits \fBQWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuserWindow\fP (\fBQWidget\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~userWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_pushButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_3_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::userWindow * \fBui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBuserwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "userWindow::userWindow (\fBQWidget\fP * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB4\fP of file \fBuserwindow\&.cpp\fP\&.
.SS "userWindow::~userWindow ()"

.PP
Definition at line \fB11\fP of file \fBuserwindow\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void userWindow::on_pushButton_3_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB22\fP of file \fBuserwindow\&.cpp\fP\&.
.SS "void userWindow::on_pushButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line \fB16\fP of file \fBuserwindow\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Ui::userWindow* userWindow::ui\fC [private]\fP"

.PP
Definition at line \fB24\fP of file \fBuserwindow\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D-College-Tour from the source code\&.
